DROP TABLE IF EXISTS FORMATION ;
CREATE TABLE FORMATION (idFormation_FORMATION INT AUTO_INCREMENT NOT NULL,
nonFormation_FORMATION VARCHAR(50),
dureeFormation_FORMATION INT,
dateDebutFormation_FORMATION DATE,
dateFinFormation_Enseigne DATE,
idFormateur_FORMATEUR **NOT FOUND**,
PRIMARY KEY (idFormation_FORMATION)) ENGINE=InnoDB;

DROP TABLE IF EXISTS FORMATEUR ;
CREATE TABLE FORMATEUR (idFormateur_FORMATEUR SERIAL AUTO_INCREMENT NOT NULL,
nom_FORMATEUR INT,
prenom_FORMATEUR INT,
PRIMARY KEY (idFormateur_FORMATEUR)) ENGINE=InnoDB;

DROP TABLE IF EXISTS SALLE ;
CREATE TABLE SALLE (idSalle_SALLE INT AUTO_INCREMENT NOT NULL,
numSalle_SALLE INT,
localisationSalle_SALLE VARCHAR(100),
disponibible_SALLE BOOL,
formation_idformation_formation **NOT FOUND**,
PRIMARY KEY (idSalle_SALLE)) ENGINE=InnoDB;

DROP TABLE IF EXISTS MATIERE ;
CREATE TABLE MATIERE (idMatiere_MATIERE VARCHAR(50) AUTO_INCREMENT NOT NULL,
nomMatiere_MATIERE VARCHAR(50),
idFormateur_FORMATEUR **NOT FOUND**(50),
PRIMARY KEY (idMatiere_MATIERE)) ENGINE=InnoDB;

ALTER TABLE FORMATION ADD CONSTRAINT FK_FORMATION_idFormateur_FORMATEUR FOREIGN KEY (idFormateur_FORMATEUR) REFERENCES FORMATEUR (idFormateur_FORMATEUR);

ALTER TABLE SALLE ADD CONSTRAINT FK_SALLE_formation_idformation_formation FOREIGN KEY (formation_idformation_formation) REFERENCES FORMATION (idFormation_FORMATION);
ALTER TABLE MATIERE ADD CONSTRAINT FK_MATIERE_idFormateur_FORMATEUR FOREIGN KEY (idFormateur_FORMATEUR) REFERENCES FORMATEUR (idFormateur_FORMATEUR);
